livingdocsIO/editable.js

- spec/clipboard.spec.js
- src/clipboard.js
The browser represents newlines in HTML as spaces, and collapses multiples spaces.
This PR normalizes pasted content. The aim being for the HTML to be as close as possible to its representation in the browser.
> Normalize newlines on paste

- src/cursor.js
- src/range-save-restore.js
- src/util/error.js
- src/util/viewport.js
https://github.com/upfrontIO/livingdocs-planning/issues/1576
This PR supersedes https://github.com/upfrontIO/editable.js/pull/150.
By just cancelling the scroll like we do, there is now an unexpected behavior. Before, when pasting multiple paragraphs it would focus on the last one. Now the view does not move.
As you said, this is a low level library and this behavior is not as counterintuitive as the one we are fixing here.
@peyerluk
> Preserve scroll position

- src/core.js
- src/dispatcher.js
The methods `editable.suspend()` and `editable.continue` can be used to temporarily remove all event listeners. But the current implementation just removed the contenteditable attributes. All the other listeners were still active. This PR also removes all other event listeners when `suspend()` is called. So no more selection change events or copy/paste events are triggered when suspend() was called.
> Fix suspend() and continue()

- src/highlight-support.js
- src/highlighting.js
- src/selection.js
Fix issue where spellcheck highlighting would remove other highlightings. The highlight marker nodes now have different attribute values.
New marker node attributes:
- Comment and whitespace highlights: `<span data-highlight="spellcheck" ...>`
- Other highlights: `<span data-highlight="highlight" ...>`
> Fix highlighting interferences

- package.json
- spec/clipboard.spec.js
- src/clipboard.js
- src/config.js
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/2965
- Issue2: https://github.com/livingdocsIO/livingdocs-planning/issues/3025
The clipboard turns relative links into absolute ones so:
`/internal/link` gets converted to `https://livingdocs.io/internal/link`
There is a new flag to turn off this behavior if the link was copied from the same context/host editable is running on.
So if a relative link was copied from `https://livingdocs.io/internal/link` it strips off the protocol, hostname and port number of a URL and turns it to `/internal/link`
If a relative link was copied from `https://somewebpage.com/internal/link` it will still convert it to an absolute one.
- new config option
```js
Editable.globalConfig({
pastedHtmlRules: {
keepInternalRelativeLinks: …
```
> Clipboard: Copy&Paste keeps links relative

- spec/clipboard.spec.js
- spec/config.spec.js
- spec/highlighting.spec.js
- spec/spellcheck.spec.js
- src/core.js
Instead of resorting to using a deep-require - a simple helper to retrieve the Editable standard configs.
- Adds `Editable.getGlobalConfig()`to retrieve the current state of the configs
> Add helper to retrieve the editable configs

- spec/highlighting.spec.js
- src/core.js
- src/cursor.js
- src/highlight-support.js
Relations:
- Backport: < add a backport link in both directions (original <-> backport) >
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/3088
If the highlighting is changing a change event should be sent. This is because some highlighting like e.g for comments is part of the content so changes should be treated the same as content changes.
With this change on the setVisibleSelection the focus shouldn't be set because otherwise on writing a comment the focus will be set on the component.
- Don't force focus on `setVisibleSelection()` anymore.
the reason is the spellcheck which use the retainVisibleCollection and come back after some time and set the focus again. We should split the spellcheck from the standard highlighting
- Update api endpoint behavior for highlights: …
> update model on remove and add highlight

- spec/cursor.spec.js
- spec/dispatcher.spec.js
- src/create-default-behavior.js
We're fighting against default browser behavior here as adding a break-tag with shift+enter at the end of a text, will automatically create two break-tags, with one being un-deletable.
Related issue that tinymc has (They have a WYSIWYG-editor): https://github.com/tinymce/tinymce/issues/4856
My suggestion is to just intervene and disallow/remove break-tags at the end of a text. This is more transparent due to the visual feedback, vs hidden `<br>` tags in the document.
Furthermore, mark all other break-tags (`<br data-editable="newline">`), because this solution has some tradeoffs as well.
- Shift+enter at the end of a line will now add `<br data-editable="remove">` instead of `<br>`
- Shift+enter now marks all the break-tags `<br data-editable="newline">`
- When creating a new line with …
> Shift enter at end of text adds data tag to the added <br> tag

- package-lock.json
- package.json
- spec/content.spec.js
- spec/selection.spec.js
- src/content.js
- src/selection.js
Add the possibility to toggle Custom elements and to detect the wrapping elements by tagName and Attributes. On this way a span can be used twice with other attributes.
- toggleTag checks on the tag and attributes
- on a selection a custom element can be toggled
> add custom elements and 

- src/selection-watcher.js
Rangy can throw in some cases an exception on the getSelection because the nativeSelection is not available.
```TypeError: Cannot read property 'rangeCount' of null
at refreshSelection (VM42172 rangy-core.js:3428)
at WrappedSelection.selProto.refresh (VM42172 rangy-core.js:3462)
at Object.getSelection (VM42172 rangy-core.js:3223)
at SelectionWatcher.syncSelection (VM42222 selection-watcher.js:83)
at SelectionWatcher.getRangeContainer (VM42222 selection-watcher.js:93)
at SelectionWatcher.getFreshSelection (VM42222 selection-watcher.js:127)
at Editable.getSelection (VM42151 core.js:365)
at Highlighting.safeHighlightMatches (VM42272 highlighting.js:217)
at eval (VM42272 highlighting.js:207)
at eval (VM42273 spellcheck-service.js:64) "Possibly unhandled rejection: {}"
```
- catch rangy …
> handling exception in getSelection

- examples/events.js
- src/cursor.js
- src/dispatcher.js
The switch event was broken due to wrong keyboard event handling.
And then there is the issue that the switch event should allow to move the cursor to the previous or next content block in the same way as the browser does when all text is in the same contenteditable.
To do this even after this PR we lack some functionality. We need to store the `x` position when a user first presses either key up or down and then send these coordinates with the switch event once the cursor reaches the boundary of the current contenteditable.
And to finish it up we would need a method to insert the cursor at the beginning or end of a contenteditable at coordinate `x`.
- 🐞 Trigger switch event again
- 🍬 The switch event now triggers when pressing key up in the first line of text and key down at the last …
> Fix switch event

- src/parser.js
I think the example called to the wrong function.
Another typo, I think, is here:
https://github.com/livingdocsIO/editable.js/blob/35e4e2a767db6351810a513bdcec4c69ee583057/src/parser.js#L189-L200
The function should be called `lastChild()` and not “latest”. However, I suspect that that’s a breaking change, within this repo and I suspect to other users of this package. So, if interested I can submit a PR and use a trampoline function to maintain compatibility — if you folks care 😉
> Fix documentation typo.

- src/create-default-behavior.js
Addresses issue https://github.com/livingdocsIO/editable.js/issues/188. According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) the `cloneNode()` default paramenter `deep` changes for different DOM and browser versions, and it should _always_ be specified. All other uses of `cloneNode()` are fine.
> Prevent accidental deep cloning.

- src/create-default-behavior.js
That’s because the first element of `blocks` was inserted at the cursor position
https://github.com/livingdocsIO/editable.js/blob/373d654c0cc214a4430bcc067a7e53b583224e41/src/create-default-behavior.js#L152
and then, if more block elements were pasted, it was iterated over _again_:
https://github.com/livingdocsIO/editable.js/blob/373d654c0cc214a4430bcc067a7e53b583224e41/src/create-default-behavior.js#L159
Fix: [shift()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift) the first `blocks` element out of the array.
> Fix paste bug in default behavior: first pasted block element was duplicated.

- README.md
- examples/index.html
- spec/spellcheck.spec.js
- src/core.js
- src/highlighting.js
The spellcheck is automatically update the highlighting after a change in the editable. This happens asynchronously and can lead to change which we will miss.
🍬fire `spellcheckUpdated` event after spellchecker has updated highlighting
> Add new highlighting change event

- spec/highlighting.spec.js
- src/core.js
- src/highlight-support.js
At the moment all highlight ranges are returned in the `getHighlightPositions()` function. Now it is possible to get only a specific type of highlights. 
Changelog
🍬add type param to `getHighlightPositions` function to get only highlightRanges from a specific type.
> Extract specific highlight ranges

- spec/dispatcher.spec.js
- spec/keyboard.spec.js
- src/create-default-behavior.js
- src/create-default-events.js
- src/dispatcher.js
- src/keyboard.js
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4185
- 🎁 Add support for "bold" events, with `ctrl + b` or `meta + b` keyboard shortcuts
- 🎁 Add support for "italic" events, with `ctrl + i` or `meta + i` keyboard shortcuts
> Handle keyboard bold and italic toggling

- spec/config.spec.js
Relations:
- Related PR's: https://github.com/livingdocsIO/editable.js/pull/208
A test failed on the last deployment which I've seen happen once before. I believe it could be related to the order in which tests are run, but I haven't been able to reproduce it locally (with `npm test` or using `drone`).
```
Editable configuration globalConfig() retreives the config FAILED
Error: Expected $.linkMarkup.name = 'a' to equal 'em'.
```
Reset config before all `globalConfig()` tests are run, in addition to after each test.
> chore(config): Update config before tests

- .babelrc
- package-lock.json
- package.json
Relations:
- Related PR's: https://github.com/livingdocsIO/editable.js/pull/208
Babel 6 removed `module.exports = Editable`, so the `require()` behaviour changed. The current release needs `require('upfront-editable').default`, and this commit restores `require('upfront-editable')` functionality. 
- 🐞 Restore `module.exports` for Node.js `require()` compatibility
> fix(babel): Add module.exports for compatibility

- spec/selection.spec.js
- src/selection.js
* 🎁 Add method to `selection`: `selection.removeChars(['«', '»', '"'])`
> feat(selection): add removeChars() method

- spec/clipboard.spec.js
- src/clipboard.js
- src/config.js
- src/quotes.js
On paste the quotation marks in a text should be replaced with quotation marks set in the config. 
- 🎁 Add quotation mark replace on paste
added config in `pastedHtmlRules`
```
replaceQuotes: {
quotes: ['“', '”'],
singleQuotes: ['‘', '’'],
apostrophe: '’'
}
```
> replace quotation marks

- .eslintrc.json
- spec/api.spec.js
- spec/node-iterator.spec.js
- src/core.js
- src/cursor.js
- src/dispatcher.js
- src/eventable.js
- src/highlight-support.js
- src/node-iterator.js
- src/util/binary_search.js
- src/util/element.js
Related:
- https://github.com/livingdocsIO/livingdocs-framework/pull/573
- https://github.com/livingdocsIO/livingdocs-editor/pull/4496
In order to support maintaining the cursor position when moving up and down with the arrow keys in between editable containers (e.g. paragraphs) we implement methods to search a character offset given a coordinate set as well as a method to create a cursor at a given character offset.
```js
const {wasFound, offset, distance} = this.editable.findClosestCursorOffset({editable, element, origCoordinates})
if (wasFound) this.editable.createCursorAtCharacterOffset({element, offset})
```
Takes an element containing text nodes and a coordinate box and uses the `left` coordinate to position a character offset in `element` that most closely matches the left …
> Provide cursor offset search and set methods

- src/cursor.js
- src/selection.js
This helper function is useful to check whether the cursor is currently inside of a certain element. For example, within links I want to ignore split and linefeed events:
```javascript
if (cursor.getParentContainer('A')) {
return;
}
```
@peyerluk, I think you had implemented a similar function in PR https://github.com/livingdocsIO/editable.js/pull/99 regarding links and not wanting to wrap a link in a link. This PR might support yours?
> Hoist helper functions from Selection into Cursor class.

- spec/content.spec.js
- src/content.js
Here's one first fix for something that broke when I've removed jQuery.
- 🐛 Fix content.isExactSelection comparison for text nodes
> Fix content.isExactSelection comparison for text nodes

- src/content.js
- src/selection.js
Extend the [selection.removeFormatting()](https://github.com/livingdocsIO/editable.js/blob/77e45729651eda118ec232c0adf603171d7686b0/src/selection.js#L202-L206) function so that it can remove nodes based on tag name _and_ class name; handy if I’d like to remove e.g. `span.foo` only.
> feat(selection): Remove nodes based on tag name and class.

- examples/events.js
- src/cursor.js
- src/dispatcher.js
- src/highlight-support.js
- src/parser.js
- src/util/dom.js
In Firefox 89 I'm getting the following error when selecting or deselecting components:
```
Uncaught TypeError: evt.target.closest is not a function
getEditableBlockByEvent webpack://@livingdocs/editor/../editable.js/lib/dispatcher.js?:271
```
This doesn't make much sense, as `closest()` has been supported in Firefox [since version 35](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#browser_compatibility), but this little check is enough to handle the issue.
> fix(events): Check event.target.closest() exists before calling

- src/dispatcher.js
- 🐛 Deregister event listeners properly by passing the capture flag/option during `removeEventListener`
> Fix keydown event deregistration

- spec/cursor.spec.js
- src/content.js
- src/cursor.js
Split the original `content.getTags()` function into two, to make its components available separately. Then make these two new functions available to the Cursor (and, thus, the Selection).
> feat(selection): Add helper functions to select tags.

- examples/index.css
- spec/dispatcher.spec.js
- src/content.js
- src/create-default-behavior.js
Before:
| Without Focus | With Focus  |
|-----------------|:-----------:|
| ![image](https://user-images.githubusercontent.com/431376/127650121-0318405f-a004-4bd0-b351-8674f7ee627a.png)      | ![image](https://user-images.githubusercontent.com/431376/127650156-2ffdbd97-7dc8-4cff-a6f2-413e85fc2960.png)    |
After:
| Without Focus | With Focus  |
|-----------------|:-----------:|
| ![image](https://user-images.githubusercontent.com/431376/127650471-7aaf3751-319f-4dcf-9208-cc0c93d51b01.png)  | ![image](https://user-images.githubusercontent.com/431376/127650489-b3ccf81c-940c-46a8-9791-3f5687555194.png) |
The cursor also shows up correctly in Chrome & Safari & Firefox.
> Use null escape instead of br tags for empty elements

- spec/content.spec.js
- spec/dispatcher.spec.js
- src/content.js
- src/create-default-behavior.js
- src/cursor.js
- src/keyboard.js
- 🐛 Do not remove newlines in between child nodes of editable blocks
- 🐛 Do not require two shift+return when appending a new line at the end of an editable block
- 🍬 Trim newlines at the start and end of editable blocks
Behavior Before:
Type text, shift return, shift return, type text. blur
| Before Blur | After Blur  |
|-----------------|:-----------:|
| ![image](https://user-images.githubusercontent.com/431376/127742367-8880f02b-1450-4732-81f9-05178cca4309.png) | ![image](https://user-images.githubusercontent.com/431376/127742345-3ab933c6-9484-454b-b3ec-19acadd9b2da.png)  |
After:
Type text, shift return, type text. blur
Results in 1 exactly newline being present.
And only one shift return is necessary to trigger a newline.
Some tests would still be nice
> Fix newline behavior

- examples/index.js
- package.json
- spec/api.spec.js
- spec/config.spec.js
- spec/create-default-events.spec.js
- spec/dispatcher.spec.js
- spec/highlighting.spec.js
- spec/spellcheck.spec.js
- src/core.js
- webpack.config.js
- The source code doesn't get transpiled into the `lib` directory anymore.
You'll either need to require `dist/editable.js` or set up your build system to support ES modules. See the comment below.
This simplifies the usage together with npm link as there's a build step less in between.
The files in the dist folder should work as before.
- The module exports changed from a default export to a named export.
For Import:
change
```
import Editable from '@livingdocs/editable.js'
```
to
```
import {Editable} from '@livingdocs/editable.js'
```
For require:
change
```
const Editable = require('@livingdocs/editable.js')
```
to
```
const {Editable} = require('@livingdocs/editable.js')
```
> Remove commonjs-based 'lib' output

- examples/index.css
- examples/index.html
- examples/index.js
- spec/dispatcher.spec.js
- src/content.js
- src/create-default-behavior.js
- src/keyboard.js
- 🐛  Use zero width spaces instead of null escape characters as they caused issues with some fonts
- 🐛 Use a more elegant solution to force a line break after a `<br>` tag. Previously backspace deleted a character too much when a newline at the end of a block got deleted.
> Improve newline behavior

- spec/dispatcher.spec.js
- spec/highlighting.spec.js
- spec/selection.spec.js
- src/core.js
- src/dispatcher.js
- src/feature-detection.js
- src/highlight-support.js
In order to support selections over multiple editable directives (e.g. over multiple paragraphs) we introduce the new event type `selectToBoundary` that is fired when:
- a selection is at the start of an editable directive (going up)
- a selection is at the end of an editable directive (going down)
- or a selection is at both ends (start and end)
Related Framework PR: https://github.com/livingdocsIO/livingdocs-framework/pull/582
The `selectToBoundary` event fires when a text selection is dragged to a boundary of an editable: either at the start, at the end or at both ends (if e.g. all text of a paragraph is selected).
The event passes the following params: `(element, event, position)`
- element is the DOM node on which the event is called
- event is the native selection event
- position …
> Introduce boundary selection event

- karma.conf.js
- spec/dispatcher.spec.js
- src/clipboard.js
- src/dispatcher.js
When copy-pasting formatted text which contains a `<strong>` tag, the tag would get lost in Chrome/Safari (but not in Firefox).
This is fixed by changing the method of retrieving pasted text from the clipboard.
Before: A hidden element with `contenteditable` attribute is focused on paste, then the clipboard content is extracted from there.
New: Clipboard content is taken from the [ClipboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent/clipboardData).
The new way seems to work reliably in all browsers and was also manually tested in Chrome, Firefox, Safari, Edge (all on macOS).
I'm not sure why specifically the `<strong>` tag was broken, maybe it's related to [this chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=546461).
After pasting, …
> Fix copy-paste of bold text

- spec/highlighting.spec.js
- src/plugins/highlighting/text-highlighting.js
In the multiline editable selection from the framework sometimes the case arises that the editable host is undefined and in turn the marker node in the text search is undefined. In that case the code went into an endless loop and crashed the browser.
If the marker node in a text search is not set, the search should not be performed and abort early.
> Fix endless loop in text-search

- src/cursor.js
Partially fixes #244 
- 🐛 Fix block focus events when using a browser zoom. There were rounding issues
Safari still has an issue with newlines at the end of an html element.
This doesn't work:
```html
<p>
Hello
</p>
<p>
World
</p>
```
And this is working:
```html
<p>Hello</p>
<p>World</p>
```
> Fix cursor move rounding issues

- spec/highlighting.spec.js
- src/plugins/highlighting/text-highlighting.js
The isElement function has added a direct dependency to the ownerDocument. This is the reason why for the spellcheck the instanceof will fail. 
🐞 support marker in highlighting with other ownerdocument
> fix isElement function

- examples/index.js
- spec/content.spec.js
- src/content.js
Content blocks were able to start with spaces before a word. This causes issues in safari as it's not possible to create cursors and get the correct position at the end.
Removing them before initialization results in more tidy content and is most likely ok.
`<p contenteditable=true>      Hello World</p>`
will result in
`<p contenteditable=true>Hello World</p>`
but only when `editable.enable(elem, true)` is used.
During extraction we apply the same logic but always.
This is another fix for #244
- 🐛 To prevent safari getClientBoundingRect issues, we'll need to remove whitespaces at the start and end of a content block
> Remove whitespaces at start and end of blocks during initialization

- spec/highlighting.spec.js
- src/highlight-support.js
Previously, the `getHighlightPositions` only returned the highlighted text as well as the text positions (not node positions!) of the range. This is handy if one wants to work with the text but not so much if the handling is with the selection itself. E.g. one might want to cut from the span nodes around the highlight which is not possible given only the text offsets.
We now also return the native range that represents the hightlight so users can freely choose how to interact with it.
> Pass native range with getHighlightPositions

- examples/index.css
- examples/index.html
- spec/content.spec.js
- spec/selection.spec.js
- src/range-save-restore.js
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4333
A link is removed when a bold tag is created around. It happens only when bold surrounds more than the link.
The problem is actually more general. Whenever a formatting tag is selected directly at the beginning (leading) or end (trailing) the marker will be set *inside* of the format tag thus destroying the HTML markup.
We use the selection range of the browser to check if the selection is directly leading or trailing a formatting tag. If so, we manually set the marker tag directly before or after the format tag in order to keep the HTML markup intact.
Manually tested on:
- Mac OSX Chrome
- Mac OSX Safari
- Mac OSX Firefox
- Windows 11 Edge
> Allow formats to be set over links if the beginning or end is at a boundary

- src/range-save-restore.js
With the fix for formats over links (https://github.com/livingdocsIO/editable.js/pull/251) we introduced a bug that markers could be set outside of the host. 
The problem was that we used `parentElement` in order to get the ranges parent instead of `commonAncestorContainer` which will always contain the resulting element to the host that contains the selection.
> Fix bug in save and restore

- spec/selection.spec.js
- src/config.js
- src/selection.js
Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4538
So far editable.js made no special handling for leading or trailing whitespaces in a selection. While in general, it is smart to not make too many assumptions for some formats leading or trailing whitespaces make very little sense. The initial case of this issue was that links leave an empty `<a>` tag with a whitespace if the "visible" part of the link is deleted. While it would be possible to use the `del` and `backspace` event to clean up such cases after every delete IMO this is the wrong way to see this.
There are formats for which leading and trailing whitespaces make no sense. For this reason we introduce a `trim` config to the standard formats that if  set to `true` will not consider leading or trailing …
> introduce trim config for formats

- spec/highlight-text.spec.js
- src/highlight-text.js
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4573
- 🐞 Fix highlighting of paragraphs with soft breaks in the multi-paragraph selection.
On the [getText()](https://github.com/livingdocsIO/editable.js/blob/e3a62f9db98eec94af392a6115fa490ac4281a5f/src/highlight-text.js#L139), which is used only in [extractText()](https://github.com/livingdocsIO/editable.js/blob/e3a62f9db98eec94af392a6115fa490ac4281a5f/src/highlight-text.js#L11), replace `<br>` with `\n` instead of an empty space.
This way in the in the [highlightText()](https://github.com/livingdocsIO/editable.js/blob/e3a62f9db98eec94af392a6115fa490ac4281a5f/src/highlight-support.js#L22), the `blockText` that comes from `extractText()` will have matches with the `text` argument that also treats `<br>`'s as …
> fix: replace <br> elements with '\n' instead of one space

- spec/dispatcher.spec.js
- src/dispatcher.js
- src/util/string.js
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-planning/issues/4587
If on an editable you add a space and then paste some text, the space added previously will be converted on a `non breaking space`.
- 🐞 Replace `non breaking spaces` with normal spaces when pasting on an `editable`.
> fix: replace &nbsp; with normal space on 'paste' event

- src/config.js
- src/content.js
Relations:
- Related PR's:
- https://github.com/livingdocsIO/editable.js/pull/246#issuecomment-1061169814
Some customers want to disable the feature that removes the leading and trailing spaces from and editable.
- 🎁  New config `trimLeadingAndTrailingWhitespaces`. With it we can configure if we want to remove or not the leading and trailing spaces from and editable.
> feat: add 'trimLeadingAndTrailingWhitespaces' config

- spec/highlighting.spec.js
- src/core.js
- src/highlight-support.js
Relations:
- Issue: If a word was repeated in a component all copies of that word were highlighted. Furthermore, if a comment was added and then text was added to the component before the highlighted comment the highlight moved
- Related PR's: [Editor PR](https://github.com/livingdocsIO/livingdocs-editor/pull/5153)
NZZ reported the case where the same word in a component was highlighted repeatedly when an article was re-oponed after highlighting and resolving. When investigating this, it turned out there were several bugs related to the saving of the start index of the comments. This PR combined with the above Editor PR aims to fix this. 
So the use cases where this bug happens is as follows:
- A user comments on a word and resolves the comment
- A user reopens the article or refreshes …
> fix(comment index): index is found with search in added case

- spec/dispatcher.spec.js
- src/dispatcher.js
- src/util/string.js
Relations:
Backport: release-2022-05 and release 2022-03
Issue: When anything was pasted into an editable with a space at the end it was pasted at the end of the component
Documentation: -
Related PR's: https://github.com/livingdocsIO/editable.js/pull/266
Motivation
NZZ noticed that when an editor cut from the end of a component and pasted it, sometimes it was pasted back to where it was cut from. This was an unexpected side effect of Muhamet's fix to remove the non breaking space at the end of editables. 
https://user-images.githubusercontent.com/76001984/173227449-178d9247-792c-4b38-b986-51349b933227.mov
Furthermore, Sternwald reported that for some users when using shift + enter properties were added to <br> tags. This is fixed with the updated check in `utils/string.js`. 
The test is …
> fix(cutandpaste): Cursor not moved

- spec/selection.spec.js
- src/clipboard.js
- src/content.js
- src/cursor.js
- src/selection.js
- Issue: https://tracking.nzzmg.ch/browse/WCMS-6398
There are two issues(videos below) related with pasting text over a selected text which contains markups like `<strong>` or `<em>`
https://user-images.githubusercontent.com/80449613/183460347-e33b442c-5426-472b-97bc-cef7f1b41c73.mov
https://user-images.githubusercontent.com/80449613/183459341-3d2662f3-4f37-487b-aca0-6ab11f48f473.mov
- 🐞 When we paste text while some other text is selected, check If the selected text is exactly surrounded by markup, and if yes delete that markup as well.
- 🐞 When we paste text while some other text is selected, check if there are markups whose text is completely within the current selection, and if yes delete that markup as well.
> fix: pasting text over selected text which contains markups

- spec/highlighting.spec.js
- src/create-default-behavior.js
Fixes: https://github.com/livingdocsIO/livingdocs-planning/issues/4773
- 🐞 Prevent cursor loss on tab switch
When switching tabs on coming back a blur event is raised on the editable.  After that the browser sets the cursor again. In our blur event we call `cleanInternals()` wich resets `innerHTML` which causes the browser to loose the cursor position and it sets the cursor to the beginning.
To prevent this we can use `document.activeElement` to check if the editable which receives the blur event is still the active element itself. If so we do an early abort and do not call `cleanInternals()`.
> Prevent cursor loss on tab switch

- spec/highlighting.spec.js
- src/highlight-support.js
🐞 Fix comment highlight when text comment was deleted
An issue was preventing the comments to be highlighted if the text of the comment was deleted. 
TextBlock is an empty string when the text was deleted, so there can't be any matches. 
The function returns immediately as there is no text to highlight in that case.
> fix: comment highlight when text is deleted

- examples/index.html
- examples/index.js
- spec/clipboard.spec.js
- spec/selection.spec.js
- src/block.js
- src/clipboard.js
- src/config.js
- src/core.js
- src/selection.js
Adds an option to configure plain text behavior per block.
- Commands like `toggleBold` won't work on selections within such a block
- Keyboard shortcuts for formatting won't work
To enable the behavior use:
`editable.add('.example', {plainText: true}` or `editable.enable('.example', {plainText: true}`
The normalize option can still be passed as second argument, or it can be included in the options parameter:
`editable.enable('.example', true)` or `editable.enable('.example', {normalize: true}`
> Support block-based plainText option

- spec/selection.spec.js
- src/selection.js
- src/util/dom.js
Relations:
- Issues:
- Fixes https://github.com/livingdocsIO/livingdocs-bugs/issues/5083
- Fixes https://github.com/livingdocsIO/livingdocs-bugs/issues/4895
We are trying to trim whitespace characters around selections for certain tags such as links, bold, italic etc. For links we add and remove span elements to save the range when the focus is lost, so we're actually dealing with text nodes for the offsets and not character offsets. For bold and italic it could be text node or character offsets that we're dealing with in the range. The code in master always assumes the offsets are characters.
- 🐞 Handle nodes and text when trimming whitespace from a selection
- 🐞 Don't wrap a collapsed selection with tags
> Handle nodes and text when trimming whitespace from a selection

- src/selection-watcher.js
- 🐛 Fix `selectionWatcher.getRangeContainer` to handle cases where there's no selection in the document
> Fix getRangeContainer to handle cases where there's no selection in the document

- spec/content.spec.js
- src/content.js
Relations:
- Related PR's: https://github.com/livingdocsIO/editable.js/pull/267
- 🐞 Fixed a bug where extracted text content didn't trim `&nbsp;` characters
Another [PR](https://github.com/livingdocsIO/editable.js/pull/267) introduced the opt-out config `trimLeadingAndTrailingWhitespaces` to disable the trimming behavior. At the same time, it also changed the trimming logic to only remove the standard whitespace character(U+0200). As a result, other whitespace characters like `U+00A0` (Unicode for `&nbsp;`) were not removed.
Depending on the browser, such characters are inserted automatically when the space key is used at the start or end of a `contenteditable` element. Since this is very common, we decided to change the trimming back to the `\s` regex character class to match a wider …
> Fix whitespace trimming

- src/clipboard.js
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-bugs/issues/5178
Copy pasting formatted text certain text/html throws an error. Although for me unclear how it can be `undefined` in the function as we check [one line before that it is not undefined](https://github.com/livingdocsIO/editable.js/blob/master/src/clipboard.js#L102) we can at least safely access it to not throw an error. 
- 🐛 Fix clipboard copy pasting formatted text throwing an error
> Fix clipboard copy pasting formatted text

- src/core.js
- src/highlight-support.js
Relations:
- Issue: https://github.com/livingdocsIO/livingdocs-bugs/issues/5225
- Related PRs: https://github.com/livingdocsIO/livingdocs-editor/pull/8659
Using `highlightText` doesn't emit emit a change event.
- 🐛 Fix emit change event on highlightText
> fix: on highlightText dispatch a change event

- spec/dispatcher.spec.js
- src/dispatcher.js
Relations:
- Fixes: #488 
- 🐛 Remove backwards compatibility for missing input events.
The logic causes issues as it loses the first change/input event.
> Remove input event backwards compatibility

- src/dispatcher.js
- src/smartQuotes.js
Relations:
- Basecamp Issue: [Link](https://3.basecamp.com/4910529/buckets/39227833/documents/8027430845)
- Related PR's: [Server PR ](https://github.com/livingdocsIO/livingdocs-server/pull/7695)
- Related PR's: [Editor UI PR ](https://github.com/livingdocsIO/livingdocs-editor/pull/9545)
Enhance text consistency and readability by automatically formatting quotation marks as users type. This ensures they match the configured preferred style.
- You need to have `livingdocs-framework`, `livingdocs-server`, `livingdocs-editor` and this branch of `editable.js` locally available
- In [`livingdocs-framework`](https://github.com/livingdocsIO/livingdocs-framework)'s `package.json`, point the `@livingdocs/editable.js` dependency to this local version of `editable.js` and then install dependencies
- …
> Smart quotes
